<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basiclist" nsURI="eu.modelwriter.examples.basiclist" nsPrefix="tol">
  <eAnnotations source="http://www.modelwriter.eu/alloyinecore/source">
    <details key="source" value="package basiclist: tol= 'eu.modelwriter.examples.basiclist'&#xA;{&#xA;&#x9;class one Memory&#xA;&#x9;{&#xA;&#x9;&#x9;property have : Requirement [*] {composes};&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;class Requirement&#xA;&#x9;{&#xA;&#x9;&#x9;property req: Requirement [*] {transitive, antisymmetric, acyclic};&#xA;&#x9;}&#xA;}"/>
    <details key="source_hash" value="1749776254"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Memory">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/cardinality">
      <details key="cardinality" value="one"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="have" ordered="false" upperBound="-1" eType="//Requirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="req" ordered="false" upperBound="-1" eType="//Requirement">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/transitive"/>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/antisymmetric"/>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/acyclic"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
